title: Dotori Craft
description: >
  도토리 크라프트는 을지로3가에 있는 가죽 공방입니다.
  디자인부터 마무리까지 한 사람이 책임지고 손바느질로 정성스럽게 제작합니다.
  또 정규 클래스나 일일 체험을 통해 가죽 제품을 직접 손으로 만들어보는 즐거움을 느낄 수 있습니다.
keywords:
  - 가죽공방
  - 가죽공예
  - 주문제작
  - 원데이클래스
  - 카드지갑
location:
  - 서울 중구 충무로 50-7 (을지로3가) 306호, 04549
  - 306, 50-7, Chungmuro 4(sa)-ga, Jung-gu, Seoul, Republic of Korea 04549

baseurl: ''
url: 'http://dotoricraft.com'

author: Yeonju, YEO
instagram: https://www.instagram.com/dotori_yeo
logo: https://dotoricraft.com/assets/img/logo-dotori-craft.png
social:
  type: 공방 # Either person or organization (defaults to person)
  name: 도토리 크라프트 # If the user or organization name differs from the site's name
  links: {  } # An array of links to social media profiles.
google:
  analytics:
  site_verification:

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
